In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("retail_sales_dataset.csv")

In [3]:
df.head()

,order_id,product,category,quantity,price,date,time,city,channel
0,ORD100000,Mouse,Accessories,two,9999,NaN,NaN,Mumbai,NaN
1,ORD100001,Keyboard,NaN,6,999,NaN,NaN,NaN,Online
2,ORD100002,router,NaN,-1,unknown,NaN,NaN,Kolkata,NaN
3,ORD100003,NaN,NaN,two,1499,2024-03-14,12:00 AM,Delhi,NaN
4,ORD100004,Smartwatch,electronics,two,499,2023/03/04,NaN,Pune,store

In [4]:
df.shape

(77000, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77000 entries, 0 to 76999
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  77000 non-null  object
 1   product   57836 non-null  object
 2   category  51542 non-null  object
 3   quantity  69212 non-null  object
 4   price     70608 non-null  object
 5   date      61552 non-null  object
 6   time      57670 non-null  object
 7   city      69925 non-null  object
 8   channel   67468 non-null  object
dtypes: object(9)
memory usage: 5.3+ MB

In [6]:
df.isnull().sum()

order_id        0
product     19164
category    25458
quantity     7788
price        6392
date        15448
time        19330
city         7075
channel      9532
dtype: int64

In [7]:
(df.isnull().mean() * 100).round(2)

order_id     0.00
product     24.89
category    33.06
quantity    10.11
price        8.30
date        20.06
time        25.10
city         9.19
channel     12.38
dtype: float64

In [8]:
df.duplicated().sum()

np.int64(2000)

In [9]:
df = df.drop_duplicates()

In [10]:
df.dtypes

order_id    object
product     object
category    object
quantity    object
price       object
date        object
time        object
city        object
channel     object
dtype: object

In [11]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [12]:
df

,order_id,product,category,quantity,price,date,time,city,channel
0,ORD100000,Mouse,Accessories,two,9999,NaT,NaN,Mumbai,NaN
1,ORD100001,Keyboard,NaN,6,999,NaT,NaN,NaN,Online
2,ORD100002,router,NaN,-1,unknown,NaT,NaN,Kolkata,NaN
3,ORD100003,NaN,NaN,two,1499,2024-03-14,12:00 AM,Delhi,NaN
4,ORD100004,Smartwatch,electronics,two,499,NaT,NaN,Pune,store
...,...,...,...,...,...,...,...,...,...
74995,ORD174995,headphones,accessories,4,NaN,2024-11-09,NaN,NaN,Store
74996,ORD174996,Smartphone,NaN,5,499,2023-01-18,00:00,Delhi,Store
74997,ORD174997,tablet,Electronics,6,799,NaT,12:00 AM,Mumbai,App
74998,ORD174998,keyboard,accessories,5,1999,NaT,NaN,Jaipur,Store
74999,ORD174999,NaN,accessories,two,4999,NaT,00:00:00,Bangalore,WEB

In [13]:
df['time'] = pd.to_datetime(df['time'], format='%I:%M %p', errors='coerce').dt.time

In [14]:
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')

In [15]:
df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [16]:
df

,order_id,product,category,quantity,price,date,time,city,channel
0,ORD100000,Mouse,Accessories,NaN,9999.0,NaT,NaT,Mumbai,NaN
1,ORD100001,Keyboard,NaN,6.0,999.0,NaT,NaT,NaN,Online
2,ORD100002,router,NaN,-1.0,NaN,NaT,NaT,Kolkata,NaN
3,ORD100003,NaN,NaN,NaN,1499.0,2024-03-14,00:00:00,Delhi,NaN
4,ORD100004,Smartwatch,electronics,NaN,499.0,NaT,NaT,Pune,store
...,...,...,...,...,...,...,...,...,...
74995,ORD174995,headphones,accessories,4.0,NaN,2024-11-09,NaT,NaN,Store
74996,ORD174996,Smartphone,NaN,5.0,499.0,2023-01-18,NaT,Delhi,Store
74997,ORD174997,tablet,Electronics,6.0,799.0,NaT,00:00:00,Mumbai,App
74998,ORD174998,keyboard,accessories,5.0,1999.0,NaT,NaT,Jaipur,Store
74999,ORD174999,NaN,accessories,NaN,4999.0,NaT,NaT,Bangalore,WEB

In [17]:
df['category'] = df['category'].str.strip().str.title()

In [18]:
df['product'] = df['product'].str.strip().str.title()

In [19]:
df['city'] = df['city'].str.strip().str.title()

In [20]:
df['channel'] = df['channel'].str.strip().str.title()

In [21]:
df['category'].fillna('Unknown', inplace=True)

C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\190213893.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['category'].fillna('Unknown', inplace=True)

In [22]:
df['product'].fillna('Unknown', inplace=True)

C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\696935017.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['product'].fillna('Unknown', inplace=True)

In [23]:
df['city'].fillna('Unknown', inplace=True)

C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\357195196.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna('Unknown', inplace=True)

In [24]:
df['channel'].fillna('Unknown', inplace=True)

C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\3433478937.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['channel'].fillna('Unknown', inplace=True)

In [25]:
df['quantity'].fillna(df['quantity'].median(), inplace=True)

C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\1755013587.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['quantity'].fillna(df['quantity'].median(), inplace=True)

In [26]:
df['price'].fillna(df['price'].median(), inplace=True)

C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\1576110267.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['price'].fillna(df['price'].median(), inplace=True)

In [27]:
df['date'].fillna(method='ffill', inplace=True)

C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\470388221.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['date'].fillna(method='ffill', inplace=True)
C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\470388221.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['date'].fillna(method='ffill', inplace=True)

In [28]:
df

,order_id,product,category,quantity,price,date,time,city,channel
0,ORD100000,Mouse,Accessories,3.0,9999.0,NaT,NaT,Mumbai,Unknown
1,ORD100001,Keyboard,Unknown,6.0,999.0,NaT,NaT,Unknown,Online
2,ORD100002,Router,Unknown,-1.0,2999.0,NaT,NaT,Kolkata,Unknown
3,ORD100003,Unknown,Unknown,3.0,1499.0,2024-03-14,00:00:00,Delhi,Unknown
4,ORD100004,Smartwatch,Electronics,3.0,499.0,2024-03-14,NaT,Pune,Store
...,...,...,...,...,...,...,...,...,...
74995,ORD174995,Headphones,Accessories,4.0,2999.0,2024-11-09,NaT,Unknown,Store
74996,ORD174996,Smartphone,Unknown,5.0,499.0,2023-01-18,NaT,Delhi,Store
74997,ORD174997,Tablet,Electronics,6.0,799.0,2023-01-18,00:00:00,Mumbai,App
74998,ORD174998,Keyboard,Accessories,5.0,1999.0,2023-01-18,NaT,Jaipur,Store
74999,ORD174999,Unknown,Accessories,3.0,4999.0,2023-01-18,NaT,Bangalore,Web

In [29]:
df['time'].fillna(method='ffill', inplace=True)

C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\596065226.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['time'].fillna(method='ffill', inplace=True)
C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\596065226.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['time'].fillna(method='ffill', inplace=True)

In [30]:
df = df[df['quantity'] > 0]
df = df[df['price'] > 0]

In [31]:
df['total_sales'] = df['quantity'] * df['price']

In [32]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 67427 entries, 0 to 74999
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     67427 non-null  object
 1   product      67427 non-null  object
 2   category     67427 non-null  object
 3   quantity     67427 non-null  float64
 4   price        67427 non-null  float64
 5   date         67425 non-null  datetime64[ns]
 6   time         67425 non-null  object
 7   city         67427 non-null  object
 8   channel      67427 non-null  object
 9   total_sales  67427 non-null  float64
dtypes: datetime64[ns](1), float64(3), object(6)
memory usage: 5.7+ MB

order_id       0
product        0
category       0
quantity       0
price          0
date           2
time           2
city           0
channel        0
total_sales    0
dtype: int64

In [33]:
df

,order_id,product,category,quantity,price,date,time,city,channel,total_sales
0,ORD100000,Mouse,Accessories,3.0,9999.0,NaT,NaT,Mumbai,Unknown,29997.0
1,ORD100001,Keyboard,Unknown,6.0,999.0,NaT,NaT,Unknown,Online,5994.0
3,ORD100003,Unknown,Unknown,3.0,1499.0,2024-03-14,00:00:00,Delhi,Unknown,4497.0
4,ORD100004,Smartwatch,Electronics,3.0,499.0,2024-03-14,00:00:00,Pune,Store,1497.0
5,ORD100005,Unknown,Accessories,2.0,2999.0,2024-03-14,00:00:00,Unknown,Web,5998.0
...,...,...,...,...,...,...,...,...,...,...
74995,ORD174995,Headphones,Accessories,4.0,2999.0,2024-11-09,00:00:00,Unknown,Store,11996.0
74996,ORD174996,Smartphone,Unknown,5.0,499.0,2023-01-18,00:00:00,Delhi,Store,2495.0
74997,ORD174997,Tablet,Electronics,6.0,799.0,2023-01-18,00:00:00,Mumbai,App,4794.0
74998,ORD174998,Keyboard,Accessories,5.0,1999.0,2023-01-18,00:00:00,Jaipur,Store,9995.0
74999,ORD174999,Unknown,Accessories,3.0,4999.0,2023-01-18,00:00:00,Bangalore,Web,14997.0

In [34]:
del df["time"]

In [35]:
df

,order_id,product,category,quantity,price,date,city,channel,total_sales
0,ORD100000,Mouse,Accessories,3.0,9999.0,NaT,Mumbai,Unknown,29997.0
1,ORD100001,Keyboard,Unknown,6.0,999.0,NaT,Unknown,Online,5994.0
3,ORD100003,Unknown,Unknown,3.0,1499.0,2024-03-14,Delhi,Unknown,4497.0
4,ORD100004,Smartwatch,Electronics,3.0,499.0,2024-03-14,Pune,Store,1497.0
5,ORD100005,Unknown,Accessories,2.0,2999.0,2024-03-14,Unknown,Web,5998.0
...,...,...,...,...,...,...,...,...,...
74995,ORD174995,Headphones,Accessories,4.0,2999.0,2024-11-09,Unknown,Store,11996.0
74996,ORD174996,Smartphone,Unknown,5.0,499.0,2023-01-18,Delhi,Store,2495.0
74997,ORD174997,Tablet,Electronics,6.0,799.0,2023-01-18,Mumbai,App,4794.0
74998,ORD174998,Keyboard,Accessories,5.0,1999.0,2023-01-18,Jaipur,Store,9995.0
74999,ORD174999,Unknown,Accessories,3.0,4999.0,2023-01-18,Bangalore,Web,14997.0

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67427 entries, 0 to 74999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     67427 non-null  object
 1   product      67427 non-null  object
 2   category     67427 non-null  object
 3   quantity     67427 non-null  float64
 4   price        67427 non-null  float64
 5   date         67425 non-null  datetime64[ns]
 6   city         67427 non-null  object
 7   channel      67427 non-null  object
 8   total_sales  67427 non-null  float64
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 5.1+ MB

In [37]:
df = df.dropna()

In [38]:
df

,order_id,product,category,quantity,price,date,city,channel,total_sales
3,ORD100003,Unknown,Unknown,3.0,1499.0,2024-03-14,Delhi,Unknown,4497.0
4,ORD100004,Smartwatch,Electronics,3.0,499.0,2024-03-14,Pune,Store,1497.0
5,ORD100005,Unknown,Accessories,2.0,2999.0,2024-03-14,Unknown,Web,5998.0
6,ORD100006,Mouse,Accessories,1.0,4999.0,2024-03-14,Bangalore,Unknown,4999.0
7,ORD100007,Unknown,Electronics,3.0,499.0,2024-03-14,Kolkata,Online,1497.0
...,...,...,...,...,...,...,...,...,...
74995,ORD174995,Headphones,Accessories,4.0,2999.0,2024-11-09,Unknown,Store,11996.0
74996,ORD174996,Smartphone,Unknown,5.0,499.0,2023-01-18,Delhi,Store,2495.0
74997,ORD174997,Tablet,Electronics,6.0,799.0,2023-01-18,Mumbai,App,4794.0
74998,ORD174998,Keyboard,Accessories,5.0,1999.0,2023-01-18,Jaipur,Store,9995.0
74999,ORD174999,Unknown,Accessories,3.0,4999.0,2023-01-18,Bangalore,Web,14997.0

In [39]:
df['date'] = df['date'].dt.date

C:\Users\akashdeep\AppData\Local\Temp\ipykernel_10316\768321261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['date'] = df['date'].dt.date

In [40]:
df

,order_id,product,category,quantity,price,date,city,channel,total_sales
3,ORD100003,Unknown,Unknown,3.0,1499.0,2024-03-14,Delhi,Unknown,4497.0
4,ORD100004,Smartwatch,Electronics,3.0,499.0,2024-03-14,Pune,Store,1497.0
5,ORD100005,Unknown,Accessories,2.0,2999.0,2024-03-14,Unknown,Web,5998.0
6,ORD100006,Mouse,Accessories,1.0,4999.0,2024-03-14,Bangalore,Unknown,4999.0
7,ORD100007,Unknown,Electronics,3.0,499.0,2024-03-14,Kolkata,Online,1497.0
...,...,...,...,...,...,...,...,...,...
74995,ORD174995,Headphones,Accessories,4.0,2999.0,2024-11-09,Unknown,Store,11996.0
74996,ORD174996,Smartphone,Unknown,5.0,499.0,2023-01-18,Delhi,Store,2495.0
74997,ORD174997,Tablet,Electronics,6.0,799.0,2023-01-18,Mumbai,App,4794.0
74998,ORD174998,Keyboard,Accessories,5.0,1999.0,2023-01-18,Jaipur,Store,9995.0
74999,ORD174999,Unknown,Accessories,3.0,4999.0,2023-01-18,Bangalore,Web,14997.0

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67425 entries, 3 to 74999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     67425 non-null  object
 1   product      67425 non-null  object
 2   category     67425 non-null  object
 3   quantity     67425 non-null  float64
 4   price        67425 non-null  float64
 5   date         67425 non-null  object
 6   city         67425 non-null  object
 7   channel      67425 non-null  object
 8   total_sales  67425 non-null  float64
dtypes: float64(3), object(6)
memory usage: 5.1+ MB

In [44]:
df.to_csv("cleaned_retail_sales_dataset.csv", index=False)